### ISSUE TITLE
CodeChef Platform Update

### ISSUE THREAD

**Issue by diveshuttam** [stopstalk/stopstalk-deployment#202]
CodeChef Updated it platform today. Now CodeChef's contests don't come up in upcoming contests list. Also this may cause a problem with ratings update.

**Comment by raj454raj** [comment]
Hey @diveshuttam : Thanks a lot for reporting. There would not be any problem in the ratings update because the submission scripts are working fine :) . I have submitted a [patch](https://github.com/nishanthvijayan/CoderCalendar/pull/45) to the API that we use for retrieving contests and hope that they will update the API soon.

**Comment by raj454raj** [comment]
Patch merged and deployed.
