### ISSUE TITLE
Spoj only shows max of 120 submissions :(

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#205]
Need a workaround to get all the submissions of a user.
Profile page provides all the attempted problems, clicking on which gives a separate page for submissions of that problem.

**Comment by Sayak9495** [comment]
@raj454raj yeah, I also noticed that they are not allowing to lookup further submission after page5. Just suggesting, if it's a new user we can scrape all his submissions from his profile page. From there I believe we can record the timestamp of that user's latest submission as well. And after that, we can scrape normally since previous submissions have been already recorded.[assuming that a user doesn't submit more than 120 submissions after that profile scraping].

**Comment by raj454raj** [comment]
@Sayak9495 : It already works that way right now. If a user has registered at the time when he/she had less than 120 submissions - all the further submissions will be in StopStalk database and hence would be shown on the profile page. We need to re-fetch the submissions for all the existing users so that their complete profile can be depicted. We tried contacting Spoj for removing that limit, but they didn't seem to be prioritising that task in near future.
As part of this task there is one way to get all the submissions which is kind of not very well performant. Any user's spoj profile there are all the solved/attempted problems clicking on which gives the submission history of that user for that problem. Only then we can optimize on it.
Let me know if you have anything unclear.
