### ISSUE TITLE
Acceptance Graph lags 

### ISSUE THREAD

**Issue by harsh-9in** [stopstalk/stopstalk-deployment#409]
Acceptance Graph lags sometimes when the activity of a user is more.

**Comment by raj454raj** [comment]
Hey @harsh-9in, This is expected behavior as of now as we have to fetch a lot of submissions and do some computations on top of them. We will keep a note of this and see if we can do to improve the time. Feel free to raise a PR if you feel something can optimize from the existing code. Closing this for now
