### ISSUE TITLE
Delete Account

### ISSUE THREAD

**Issue by namancoder** [stopstalk/stopstalk-deployment#442]
Add the option to delete your account on stopstalk.

**Comment by Tanjim131** [comment]
Any update on this?

**Comment by sanchitverma168** [comment]
Any Update till  now?

**Comment by raj454raj** [comment]
Hey guys, currently users can empty their handles if they don't want their progress to be shown on StopStalk. This is highly discouraged and beats the purpose of StopStalk.

Our mission is to aggregate the data across platforms and show the progress at one place so that the user or their friends can indulge into a great learning experience which makes you better at programming. Not to mention, the data shown on StopStalk is already public so anyone can still check profiles on various websites anyway.

In the future we might add a deactivate option but we are still evaluating it if it really aligns with what we started with. Hope this helps.
